# Atom Lite Balboa Spa Monitor - ESPHome Configuration for Atom Lite + Tail485
# Based on M5Tough config, adapted for Atom Lite hardware

esphome:
  name: !secret device_name
  friendly_name: !secret friendly_name
  build_path: .build/esphome_atomlite_balboa_spa

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    uart.arduino_esp32: WARN
    sensor: WARN
    template.sensor: WARN

# Enable Home Assistant API
api:
  encryption:
    key: "FffAUQcept5X3djf8KOy5RPfPjIJM2Kcm64jokfU+CI="
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "AtomLite-Balboa-Spa"
    password: !secret fallback_hotspot_password

captive_portal:

web_server:
  port: 80
  include_internal: true
  local: true
  # auth:
  #   username: !secret web_username
  #   password: !secret web_password

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_retain: false
  topic_prefix: home/atomlite-balboa-spa
  birth_message:
    topic: home/atomlite-balboa-spa/LWT
    payload: "online"
    retain: true
  will_message:
    topic: home/atomlite-balboa-spa/LWT
    payload: "offline"
    retain: true

ota:
  - platform: esphome
    # Uncomment the next line and set ota_password in secrets.yaml for password protection
    # password: !secret ota_password

uart:
  id: spa_uart_bus
  tx_pin: GPIO26  # Tail485 TX pin
  rx_pin: GPIO32  # Tail485 RX pin
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 1024

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Chicago"

external_components:
  - source: ./components
    components: [balboa_spa]


balboa_spa:
  id: spa
  uart_id: spa_uart_bus
  spa_temp_scale: F

climate:
  - platform: balboa_spa
    balboa_spa_id: spa
    name: "Spa Thermostat"
    id: spa_thermostat
    visual:
      min_temperature: 62 °F
      max_temperature: 105 °F  
      temperature_step: 0.5 °F

switch:
  - platform: balboa_spa
    balboa_spa_id: spa
    jet1:
      name: "Spa Jet 1"
      id: spa_jet1
      icon: "mdi:turbine"
      on_turn_on:
        - logger.log: "Jet 1 turned ON"
      on_turn_off:
        - logger.log: "Jet 1 turned OFF"
    jet2:
      name: "Spa Jet 2"
      id: spa_jet2
      icon: "mdi:turbine"
      on_turn_on:
        - logger.log: "Jet 2 turned ON"
      on_turn_off:
        - logger.log: "Jet 2 turned OFF"
    light:
      name: "Spa Light"
      id: spa_light
      icon: "mdi:lightbulb"
      on_turn_on:
        - logger.log: "Light turned ON"
      on_turn_off:
        - logger.log: "Light turned OFF"

sensor:
  - platform: balboa_spa
    balboa_spa_id: spa
    heatstate:
      name: "Spa Heat State"
      id: spa_heat_state
      icon: "mdi:thermometer"
      filters:
        - throttle: 2s
    circulation:
      name: "Spa Circulation"
      id: spa_circulation
      icon: "mdi:rotate-3d-variant"
      filters:
        - throttle: 5s
    restmode:
      name: "Spa Rest Mode"
      id: spa_rest_mode
      icon: "mdi:sleep"
      filters:
        - throttle: 5s
    spa_clock_hour:
      name: "Spa Clock Hour"
      id: spa_clock_hour
      icon: "mdi:clock-time-four-outline"
      filters:
        - throttle: 5s
    spa_clock_minute:
      name: "Spa Clock Minute"
      id: spa_clock_minute
      icon: "mdi:clock-time-four-outline"
      filters:
        - throttle: 5s
  - platform: template
    name: "Spa Current Temperature"
    id: spa_current_temp
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      if (id(spa_thermostat).current_temperature != NAN) {
        return id(spa_thermostat).current_temperature * 1.8 + 32.0;
      } else {
        return {};
      }
    filters:
      - filter_out: nan
      - throttle: 10s
  - platform: template
    name: "Spa Target Temperature"
    id: spa_target_temp
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      if (id(spa_thermostat).target_temperature != NAN) {
        return id(spa_thermostat).target_temperature * 1.8 + 32.0;
      } else {
        return {};
      }
    filters:
      - filter_out: nan
      - throttle: 10s
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
    entity_category: diagnostic
  - platform: uptime
    name: "Uptime"
    update_interval: 120s
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Device Status"
    entity_category: diagnostic
  - platform: balboa_spa
    filter1_active:
      name: "Filter 1 Enabled"
      id: spa_filter1_active
      icon: "mdi:filter"
      entity_category: diagnostic
    filter2_active:
      name: "Filter 2 Enabled"
      id: spa_filter2_active
      icon: "mdi:filter"
      entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      update_interval: 60s
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
      update_interval: 60s
    mac_address:
      name: "MAC Address"
      entity_category: diagnostic
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic
  - platform: template
    name: "Spa Time"
    id: spa_time
    lambda: |-
      int hour = (int)id(spa_clock_hour).state;
      int minute = (int)id(spa_clock_minute).state;
      if (hour < 0 || hour > 23 || minute < 0 || minute > 59) {
        return {};
      }
      char buf[6];
      snprintf(buf, sizeof(buf), "%02d:%02d", hour, minute);
      return {buf};
    update_interval: 120s
    entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
  - platform: template
    name: "Sync Spa Time"
    id: sync_spa_time
    entity_category: diagnostic
    on_press:
      then:
        - lambda: |-
            auto now = id(sntp_time).now();
            int hour = now.hour;
            int minute = now.minute;
            id(spa)->set_hour(hour);
            id(spa)->set_minute(minute);

interval:
  - interval: 60s
    then:
      - logger.log: "Spa communication check - monitoring for stability" 