name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install ESPHome
      run: |
        pip install esphome
        
    - name: Build firmware
      run: |
        esphome compile esphome-balboa-spa.yaml
      env:
        ESPHOME_NOGIT: 1
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Balboa Spa ESPHome Component Release
          
          ### What's New
          - Optimized performance and reduced resource usage
          - Fixed temperature display issues
          - Enhanced error handling and communication reliability
          - Improved filter monitoring capabilities
          
                     ### Installation
           ```yaml
           external_components:
             - source: https://github.com/poedenon/esphome-balboa-spa
               components: [balboa_spa]
           ```
           
           ### Documentation
           See the [README](https://github.com/poedenon/esphome-balboa-spa) for full documentation.
        draft: false
        prerelease: false 